name: "Continuous Benchmarking with Daisytuner"
description: "A GitHub Action for Continuous Benchmarking with Daisytuner."
author: "Daisytuner"
inputs:
  base_image:
    description: "Base image for the job."
    required: true
  partition:
    description: "Partition for the job."
    required: true
  build:
    description: "Section to install dependencies and build the project."
    required: true
  stage:
    description: "Section to build benchmarks."
    required: true
  run:
    description: "Section to run benchmarks."
    required: true
  timeout:
    description: "Timeout for the job."
    required: true
runs:
  using: "node16"
  main: "dist/index.js"