name: Release GitHub Action

on:
  push:
    tags:
      - 'v*.*.*' # Matches tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Build the action
    - name: Build action
      run: npm run build

    # Temporarily include dist/ and commit it
    - name: Prepare dist folder for release
      run: |
        git config --global user.email "release@daisytuner.com"
        git config --global user.name "Release Bot"

        echo "Removing dist/ from .gitignore"
        sed -i '/dist\//d' .gitignore
        git add dist
        git commit -m "Include dist/ for release ${{ github.ref_name }}"

    # Push the dist folder to the release tag
    - name: Push dist folder with tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -f ${{ github.ref_name }}
        git push origin ${{ github.ref_name }} --force

    # Update the major version tag (e.g., v1)
    - name: Update major version tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        MAJOR_TAG=$(echo "${{ github.ref_name }}" | cut -d. -f1)
        git tag -f $MAJOR_TAG
        git push origin --force $MAJOR_TAG
