name: Release GitHub Action

on:
  push:
    tags:
      - 'v*.*.*' # Matches semantic version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies
    - name: Install dependencies
      run: npm ci

    # Build the action
    - name: Build action
      run: npm run build

    # Push changes to dist/ (if using pre-built code)
    - name: Commit and push dist folder
      if: github.ref_type == 'tag'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add dist
        git commit -m "Release ${{ github.ref_name }}"
        git push

    # Create or update the major version tag (e.g., v1)
    - name: Update major version tag
      if: github.ref_type == 'tag'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        MAJOR_TAG="v${{ github.ref_name%%.* }}"
        git tag -f $MAJOR_TAG
        git push origin --force $MAJOR_TAG
